name: join-me-at-event

services:

  discovery-service:
    build: infra/discovery-service
    hostname: discovery-service
    ports:
      - "8761:8761"
    networks:
      - join-me-at-event
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

  configuration-service:
    build: infra/config-service
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - join-me-at-event
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

  gateway-service:
    build: infra/gateway-service
    depends_on:
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - join-me-at-event
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

networks:
  join-me-at-event:
    name: join-me-at-event
