spring:
  application:
    name: gateway-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configuration-service
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 30000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
