spring:
  application:
    name: configuration-service
  main:
    banner-mode: off
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/infra/{application}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
server:
  port: 8888
